In [9]:
import pandas as pd
import numpy as np

mcdonalds = pd.read_csv('../Labs files/course-files/mcdonalds.csv',
                       usecols=['Category', 'Item', 'Calories', 'TotalFat'])
mcdonalds.head()

    Category                              Item  Calories  TotalFat
0  Breakfast                      Egg McMuffin       300      13.0
1  Breakfast                 Egg White Delight       250       8.0
2  Breakfast                  Sausage McMuffin       370      23.0
3  Breakfast         Sausage McMuffin with Egg       450      28.0
4  Breakfast  Sausage McMuffin with Egg Whites       400      23.0

In [10]:
excelWriter = pd.ExcelWriter("mcdonalds-excel.xlsx")

In [11]:
mcdonalds.to_excel(excelWriter,index=False,sheet_name='Menu')

In [12]:
excelWriter.save()

/var/folders/rz/24qlfvg126sfp2zf4589lt9h0000gn/T/ipykernel_47875/2958467003.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  excelWriter.save()

In [13]:
imported_1 = pd.read_excel("mcdonalds-excel.xlsx",sheet_name='Menu')

In [14]:
imported_1

,Category,Item,Calories,TotalFat
0,Breakfast,Egg McMuffin,300,13.0
1,Breakfast,Egg White Delight,250,8.0
2,Breakfast,Sausage McMuffin,370,23.0
3,Breakfast,Sausage McMuffin with Egg,450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0
...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),510,17.0
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),690,23.0
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),340,11.0
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),810,32.0
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),410,16.0

In [16]:
imported_1['Calories'] = imported_1['Calories']/2
imported_1.head()

    Category                              Item  Calories  TotalFat
0  Breakfast                      Egg McMuffin      75.0      13.0
1  Breakfast                 Egg White Delight      62.5       8.0
2  Breakfast                  Sausage McMuffin      92.5      23.0
3  Breakfast         Sausage McMuffin with Egg     112.5      28.0
4  Breakfast  Sausage McMuffin with Egg Whites     100.0      23.0

In [17]:
imported_1.to_excel(excelWriter, sheet_name='Menu_Light', index=False)

In [18]:
excelWriter.save()

/var/folders/rz/24qlfvg126sfp2zf4589lt9h0000gn/T/ipykernel_47875/2958467003.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  excelWriter.save()

In [22]:
final = pd.read_excel("mcdonalds-excel.xlsx",sheet_name=[0,1])

In [24]:
len(final)

2

In [25]:
final[1]

,Category,Item,Calories,TotalFat
0,Breakfast,Egg McMuffin,75.0,13.0
1,Breakfast,Egg White Delight,62.5,8.0
2,Breakfast,Sausage McMuffin,92.5,23.0
3,Breakfast,Sausage McMuffin with Egg,112.5,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,100.0,23.0
...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),127.5,17.0
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),172.5,23.0
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),85.0,11.0
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),202.5,32.0
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),102.5,16.0